image: maven:alpine
stages:
  - build
  - test
maven-build:
  tags:
    - comp2100
  stage: build
  script: mvn clean package -Dmaven.test.skip=true
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - target
      - ~/.m2

maven-test:

  tags:
    - comp2100
  stage: test
  script: mvn test
  artifacts:
    when: always
    reports:
      junit:
        - build/test-results/test/**/TEST-*.xml

docker-build:
  # Use the official docker image.
  tags:
    - comp2100
  image: docker:latest
  stage: build
  services:
    - docker:dind
  variables:
    DOCKER_IMAGE_NAME: roguelike-docker
  before_script:
    - docker login -u "taidn2003" -p "Taidn_^2003"
  script:
    - docker build --tag "roguelike-docker" .
    - docker tag roguelike-docker:latest taidn2003/roguelike-docker:latest
    - docker push taidn2003/roguelike-docker:latest
  rules:
    - if: $CI_COMMIT_BRANCH
      exists:
        - Dockerfile
