image: maven:alpine
stages:
  - build
  - test
maven-build:
  tags:
    - comp2100
  stage: build
  script: mvn clean package -Dmaven.test.skip=true
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - target
      - ~/.m2

maven-test:

  tags:
    - comp2100
  stage: test
  script: mvn test
  artifacts:
    when: always
    reports:
      junit:
        - build/test-results/test/**/TEST-*.xml

docker-build:
  # Use the official docker image.
  tags:
    - comp2100
  image: docker:latest
  stage: build
  services:
    - docker:dind
  variables:
    DOCKER_IMAGE_NAME: registry.gitlab.com/my-project:feature-x
  before_script:
    - docker login -u "taidn2003" -p "Taidn_^2003" registry.gitlab.com
  script:
    - docker build --pull -t "registry.gitlab.com/my-project:feature-x" .
    - docker push "registry.gitlab.com/my-project:feature-x"
    - |
      if [[ "feature-x" == "main" ]]; then  # Assuming "main" is the default branch
        docker tag "registry.gitlab.com/my-project:feature-x" "registry.gitlab.com/my-project:latest"
        docker push "registry.gitlab.com/my-project:latest"
      fi
  # Run this job in a branch where a Dockerfile exists
  rules:
    - if: $CI_COMMIT_BRANCH
      exists:
        - Dockerfile
